// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytprggtsxqipylzkgmos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0cHJnZ3RzeHFpcHlsemtnbW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTU1MzIsImV4cCI6MjA3MDA5MTUzMn0.PbE0qQAA6t8DZORrnSPGbpLMMIp2ykRUxj62NSxmwS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});